# SPDX-License-Identifier: MIT

# CI that builds this nodejs module

name: ci

on:
  pull_request:
  push:
    branches: [master]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-13
        qt:
          - version: 5.15.2
            preset: dev
          - version: 6.5.0
            preset: dev6
          - version: 6.7.1
            preset: dev6
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: 18.x
      - name: Install dependencies
        run: npm install --loglevel verbose

      - name: tsc
        run: node_modules/.bin/tsc

      - name: Install ninja-build tool
        uses: turtlesec-no/get-ninja@main

      - name: Make sure MSVC is found when Ninja generator is in use
        if: ${{ runner.os == 'Windows' }}
        uses: ilammy/msvc-dev-cmd@v1

      - name: Install Qt ${{ matrix.qt.version }}
        uses: jurplel/install-qt-action@v3
        with:
          version: ${{ matrix.qt.version }}
          cache: true

      - name: Build Qt test
        run: |
          cmake --preset=${{ matrix.qt.preset }} -S test/qt_test/
          cmake --build test/qt_test/build-dev/

      - name: Run test
        run: node out/test.js
